### ISSUE TITLE
数据多样性

### ISSUE THREAD

**Issue by linzehua** [KeSpeech/KeSpeech#1]
为什么只选取长江以北的地区数据呢？

**Comment by tzyll** [comment]
这批数据是按官话次方言的分布采集的，也有长江中下游城市。

**Comment by linzehua** [comment]
> 这批数据是按官话次方言的分布采集的，也有长江中下游城市。

原来如此👍。请问有没有计划扩展到口音更严重的地区呢？比如广普，川普

**Comment by tzyll** [comment]
> > 这批数据是按官话次方言的分布采集的，也有长江中下游城市。
> 
> 原来如此👍。请问有没有计划扩展到口音更严重的地区呢？比如广普，川普

数据里是有西南官话的，粤语这些暂无计划。
