### ISSUE TITLE
no response using my edu email

### ISSUE THREAD

**Issue by dragen1860** [KeSpeech/KeSpeech#3]
Dear author:
  Thanks for making it public for the whole audio community. It helps a lot.
   However, when i followed your guide and sent email using my edu mailbox, no response from you at all. I felt really furstrated and curious any extra information required to download the dataset. Please kinldy give some guide on how to able to donwload the dataset. Thank you very much.

**Comment by tzyll** [comment]
The company's legal depart considers much, sorry about that.
The [Ethics Review](https://openreview.net/forum?id=b3Zoeq2sCLq&noteId=ayoDevslhL) shows the considerations.

**Comment by YQ-Lin** [comment]
So, would you please show us when and how could download the dataset? Thank you very much.

**Comment by YQ-Lin** [comment]
> The company's legal depart considers much, sorry about that.
> The [Ethics Review](https://openreview.net/forum?id=b3Zoeq2sCLq&noteId=ayoDevslhL) shows the considerations.

So, would you please show us when and how could download the dataset? Thank you very much.

**Comment by tzyll** [comment]
@YQ-Lin @dragen1860 Hi, you may download the data now, your best.
