### ISSUE TITLE
Kaggle等赛事使用此数据集

### ISSUE THREAD

**Issue by lhwcv** [KeSpeech/KeSpeech#9]
你好，
   首先感谢你们的工作。
   请问除了在论文研究中使用KeSpeech并引用，可以在Kaggle 等研究性赛事中使用该数据集并引用吗

**Comment by tzyll** [comment]
研究性质的可以，遵循协议即可。

**Comment by lhwcv** [comment]
收到，感谢回复

**Comment by lhwcv** [comment]
@tzyll  具体所指的赛事是这个， 是一个方言距离度量研究类的赛事： https://ai.ppdai.com/mirror/goToMirrorDetailSix?mirrorId=30&tabindex=1
 但是它有赛事奖金， 这个不影响对吧？

**Comment by tzyll** [comment]
不影响
